### PR TITLE
Better indentation of adjacent strings in argument lists.

### LINKED ISSUE #799: adjacent  concat strings in arg lists lost indention - Regression with 1.2.5 (SDK 2.2.1-dev.3.0)
```diff
 @ShouldThrow(
   'Could not generate `toJson` code for `watch`.\n'
-      'None of the provided `TypeHelper` instances support the defined type.',
+  'None of the provided `TypeHelper` instances support the defined type.',
   configurations: ['default'],
 )
```

### PR DESCRIPTION
**Pull request by munificent**
Fix #799. See the CHANGELOG diff for details. The relevant examples are:

1.2.4:

```dart
function(
    "adjacent"
    "string");

function(
  "adjacent"
      "string", // Not great.
);

function(
    "adjacent"
    "string",
    "another");

function(
  "adjacent"
      "string",
  "another",
);
```

1.2.5:

```dart
function(
    "adjacent"
        "string"); // Regression, but consistent with trailing comma.

function(
  "adjacent"
      "string",
);

function(
    "adjacent"
        "string", // Uintentional, but an improvement.
    "another");

function(
  "adjacent"
      "string", // Unchanged.
  "another",
);
```

Now:

```dart
function(
    "adjacent"
    "string"); // No indent, since not needed to distinguish args.

function(
  "adjacent"
  "string", // Consistent with non-trailing.
);

function(
    "adjacent"
        "string", // Intentional, distinguishes from next string.
    "another");

function(
  "adjacent"
      "string", // Consistent with non-trailing.
  "another",
);
```

### CODE REVIEW

File: lib/src/source_visitor.dart [hunk 1]
```diff
@@ -186,9 +186,72 @@ class SourceVisitor extends ThrowingAstVisitor {
...
+    //
+    //     test(
+    //         "A very long test description..."
+    //             "this indentation looks bad.", () { ... });
+    //
+    // To balance these, we omit the indentation when an adjacent string
+    // expression is the only string in an argument list.
+    var shouldNest = true;
+
+    isString(AstNode node) => node is StringLiteral || node is AdjacentStrings;
```
Comment (a14n) [inline lib/src/source_visitor.dart]: `AdjacentStrings` been a `StringLiteral` you can keep only the left hand side.

```
/// A string literal expression.
///
///    stringLiteral ::=
///        [SimpleStringLiteral]
///      | [AdjacentStrings]
///      | [StringInterpolation]
///
/// Clients may not extend, implement or mix-in this class.
abstract class StringLiteral implements Literal {
  /// Return the value of the string literal, or `null` if the string is not a
  /// constant string without any string interpolation.
  String get stringValue;
}
```

Comment (munificent) [reply lib/src/source_visitor.dart]: Fixed in 1.2.7. Thanks for pointing that out!
