### PR TITLE
Correct indentation on parameters with both metadata and default values.

### LINKED ISSUE #1461: [tall] Incorrect indentation with multiple annotations on a parameter
I'm migrating regression tests and the tall style produces:

```dart
greet(
  @Rest(valueHelp: 'who', help: 'Name(s) to greet.') List<String> who, {
  @Group.start(title: 'Output')
      @Option(help: 'How many !\'s to append.')
      int enthusiasm:
      0,
  @Flag(abbr: 'l', help: 'Put names on separate lines.') bool lineMode: false,
  @Option(name: 'greeting', help: 'Alternate word to greet with e.g. "Hi".')
      String salutation:
      'Hello',
}) {}
```

There are several things wrong here:

* The subsequent `@Option` annotations shouldn't be indented.
* The parameter shouldn't be indented.
* There's no reason to split at the `:`.

### PR DESCRIPTION
**Pull request by munificent**
The AST node for a parameter with both metadata and a default value looks like:

    DefaultValueFormalParameter
      FormalParameter

The inner node has the metadata and the outer one has the default value. Prior to this PR, that meant that we'd create an AssignPiece for the default value whose left-hand side piece was the function parameter and its metadata. That meant that when the metadata split, the outer AssignPiece would be forced to split.

This slightly awkward change makes the piece structure reflect how the user (and, alas, not Analyzer) thinks of the syntax where the metadata is part of the entire parameter and the default value is inside the parameter.

Fix #1461.

### CODE REVIEW

**Comment by srawlins** [comment]
Woohoo! Just for paper-trail purposes, I believe this will fix https://github.com/dart-lang/dart_style/issues/558 when Tall Style is The Style.

File: lib/src/front_end/piece_factory.dart [hunk 1]
```diff
@@ -604,10 +613,37 @@ mixin PieceFactory {
...
+
+      pieces.add(AssignPiece(
+          left: parameter,
+          operatorPiece,
+          valuePiece,
+          canBlockSplitRight: value.canBlockSplit));
+    } else {
+      // No default value.
+      pieces.add(parameter);
+    }
```
Comment (natebosch) [inline lib/src/front_end/piece_factory.dart:639]: Consider refactoring to a guard clause and reducing indentation on the interesting path.

```suggestion
    if (defaultValue == null) {
      pieces.add(parameter);
      return;
    }
    var (separator, value) = defaultValue;
    var operatorPiece = pieces.build(() {
      if (separator.type == TokenType.EQ) pieces.space();
      pieces.token(separator);
      if (separator.type != TokenType.EQ) pieces.space();
    });

    var valuePiece = nodePiece(value, context: NodeContext.assignment);

    pieces.add(AssignPiece(
        left: parameter,
        operatorPiece,
        valuePiece,
        canBlockSplitRight: value.canBlockSplit));
```

**Review by natebosch — APPROVED** [review]

**Review by kallentu — APPROVED** [review]

File: lib/src/front_end/piece_factory.dart (hunk 1 above)
Comment (munificent) [reply lib/src/front_end/piece_factory.dart]: Great idea, thanks!
